### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by josephbosire** [lmaccherone/node-localstorage#13]
Seems this library is not compatible with the latest version of nodejs as this function has been deprecated and removed in favor of the openSync function and so the module doesnt work anymore

**Comment by lmaccherone** [comment]
I just now changed it in version 0.6.0. The deprecated fs.existsSync() function that has been deprecated in node.js v4.0 is no longer a dependency. Note, it was not failing on node.js 4.0 prior to the removal of this dependency because node.js deprecated it but didn't actually remove it. I suspect that we'd get a deprecated warning for a while before they actually removed it in a later version. Regardless, thanks for reporting this so this module stays current.
