### ISSUE TITLE
`TypeError: Proxy.create is not a function` on Node.js v6.0.0-rc.1

### ISSUE THREAD

**Issue by Lange** [lmaccherone/node-localstorage#20]
Hi there,

Node.js v6.0.0-rc.1 ships with a version of V8 that supports [ES2015 Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Because of this, [LocalStorage.coffee#L70-L85](https://github.com/lmaccherone/node-localstorage/blob/master/LocalStorage.coffee#L70-L85) are executed and throw an error, as `Proxy.create` is indeed not the way that ES2015 Proxies are instantiated. Removing this block prevents the error from being thrown, and the library seems to function as normal.

Links:
 - [Node.js v6.0.0-rc.1 downloads page](https://nodejs.org/download/rc/v6.0.0-rc.1/)

Thanks!

**Comment by lmaccherone** [comment]
Hi Lange,

It appears that v6 is not installable via nvm at the moment. Do you know if I install it, if it will stomp on my usage of nvm? If so, then how do you recommend isolating it? Docker? or just installing it in a particular folder. I'm not sure where nvm installs its version.

**Comment by Lange** [comment]
Hm, I'm not sure how one would  go about installing v6-rc.1 in a manner which would not interfere with their nvm installation. I'm okay with waiting until v6 is available on nvm before this issue can be investigated. I'm perfectly okay running on a fork for a week or two until then.

**Comment by lmaccherone** [comment]
OK. I reverted the experimental  associative array and dot-property syntax. The API for Proxy changed with node.js v6.x which broke it. Then when I switched to the new Proxy syntax, it broke the EventEmitter functionality. I tried for a bit to fix that but couldn't figure it out in the time I had. So, because it's experimental, I figured it was best to revert that functionality while I figure it out. I suspect there are more folks who will play with node.js v6.x than are experimenting with the old Proxy under harmony. I will restore associative array syntax once I know how to fix the issue with EventEmitter. I may have to wait until v6.x comes out of release candidate mode, though.

**Comment by lmaccherone** [comment]
Leaving this open until I can get back to fix it with the associative array syntax under the new Proxy API and not break EventEmitter functionality.

**Comment by highfeed** [comment]
+1

**Comment by lmaccherone** [comment]
@highfeed, should I take your "+1" to mean that you would love associative array syntax?

**Comment by highfeed** [comment]
I have the same problem

`TypeError: Proxy.create is not a function
  at JSONStorage.LocalStorage [as constructor]`

**Comment by lmaccherone** [comment]
Hmm, that should be fixed in the latest. I reverted all references to Proxy. What version are you using?

**Comment by highfeed** [comment]
Already latest :) All good.

**Comment by lmaccherone** [comment]
Does "All good" mean that you upgraded to latest and the issue went away?

**Comment by highfeed** [comment]
Yes.
