### ISSUE TITLE
After what seems to be a successful save to local-storage from the server, i cant seem to find it in my dev console on the browser. Help please

### ISSUE THREAD

**Issue by nleibow** [lmaccherone/node-localstorage#26]

**Comment by lmaccherone** [comment]
That's because node-localstorage runs only server-side in node.js and not in your browser. If you call LocalStorage from the browser, then you'll see it in your dev console. To view the results of a server-side use of node-localstorage, you'd have to look in the folder used as storage. You specify this explicitly when instantiating the object. My tests tend to use `"./scratch"`.
