### ISSUE TITLE
for each client, does it accept different value with the same key like native ls?

### ISSUE THREAD

**Issue by clouditable** [lmaccherone/node-localstorage#39]

**Comment by lmaccherone** [comment]
Just like the browser native LocalStorage, node-localstorage can keep two or more instances isolated. However, in the browser, it does it automatically by domain of the web page and node-localstorage does it by whatever scratch location you specify when you instantiate it. To keep them isolated specify different scratch locations.

Conversely, it works perfectly as expected if you specify the same location from two different instances as long as they are in the same process.

I don't think this is what you are asking, but, if you instantiate two different instances and point them at the same scratch location (simulating same domain) but they are not in the same node.js process, it won't work as expected. Sets from the two processes will overwrite each other OK as you'd expect but gets will return null if set from one but not the other. We've thought of implementing file watcher capability to deal with this but haven't because nobody has asked for it yet. If this is what you need though, let me know and I'll look into implementing it.

**Comment by clouditable** [comment]
i have multiple clients and every client has address data for food delivery. i'm using react js with server side rendering and i need these delivery details on server side short-term. i dont know what is the best option

**Comment by clouditable** [comment]
actually i use node-localstorage now dynamically, every client has a deviceId and I can manipulate it using this state like this;
`
localStorage.setItem("clientData-${deviceId}")
`
but I'm not sure it's the right one for the app
