### ISSUE TITLE
Why node-localstorage over localStorage

### ISSUE THREAD

**Issue by kopax** [lmaccherone/node-localstorage#59]
Hi @Imaccherone, 

It's not written anywhere in the `README.md` and I am used to use `localStorage` package on npm since node which provide the localStorage for node, see https://www.npmjs.com/package/localStorage

What are the benefits of using `node-localStorage` except the max filesize configurable limit?

Thanks for clarifying,

**Comment by lmaccherone** [comment]
Of course, it's up to you. My implementation gets roughly 10x the downloads of the one you reference. Mine is a more complete implementation including things the other does not like events, serialization to disk, associative array syntax, and dot property syntax. Mine is still very small but the other is smaller still due to the missing features.
